// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FindObjectOKCode is the HTTP code returned for type FindObjectOK
const FindObjectOKCode int = 200

/*
FindObjectOK OK

swagger:response findObjectOK
*/
type FindObjectOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewFindObjectOK creates FindObjectOK with default headers values
func NewFindObjectOK() *FindObjectOK {

	return &FindObjectOK{}
}

// WithPayload adds the payload to the find object o k response
func (o *FindObjectOK) WithPayload(payload string) *FindObjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find object o k response
func (o *FindObjectOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindObjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
FindObjectDefault Any Error

swagger:response findObjectDefault
*/
type FindObjectDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewFindObjectDefault creates FindObjectDefault with default headers values
func NewFindObjectDefault(code int) *FindObjectDefault {
	if code <= 0 {
		code = 500
	}

	return &FindObjectDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find object default response
func (o *FindObjectDefault) WithStatusCode(code int) *FindObjectDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find object default response
func (o *FindObjectDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find object default response
func (o *FindObjectDefault) WithPayload(payload string) *FindObjectDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find object default response
func (o *FindObjectDefault) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindObjectDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
