// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Сервис хранения ключей",
    "title": "Сервис хранения ключей",
    "termsOfService": "http://swagger.io/terms/",
    "version": "2.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/objects/{key}": {
      "get": {
        "description": "Получить объект из хранилища по ключу",
        "consumes": [
          "text/plain"
        ],
        "produces": [
          "text/plain"
        ],
        "operationId": "FindObject",
        "parameters": [
          {
            "type": "string",
            "description": "Ключ",
            "name": "key",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Any Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "put": {
        "description": "Добавить объект в хранилище по ключу",
        "consumes": [
          "text/plain"
        ],
        "produces": [
          "text/plain"
        ],
        "operationId": "AddObject",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "type": "string",
            "description": "Ключ",
            "name": "key",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "description": "Ключ",
            "name": "expires",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "default": {
            "description": "Any Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Сервис хранения ключей",
    "title": "Сервис хранения ключей",
    "termsOfService": "http://swagger.io/terms/",
    "version": "2.0"
  },
  "host": "localhost",
  "basePath": "/",
  "paths": {
    "/objects/{key}": {
      "get": {
        "description": "Получить объект из хранилища по ключу",
        "consumes": [
          "text/plain"
        ],
        "produces": [
          "text/plain"
        ],
        "operationId": "FindObject",
        "parameters": [
          {
            "type": "string",
            "description": "Ключ",
            "name": "key",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Any Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "put": {
        "description": "Добавить объект в хранилище по ключу",
        "consumes": [
          "text/plain"
        ],
        "produces": [
          "text/plain"
        ],
        "operationId": "AddObject",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "type": "string",
            "description": "Ключ",
            "name": "key",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "description": "Ключ",
            "name": "expires",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "default": {
            "description": "Any Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
}
