// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"github.com/alexjurev/vault-service/pkg/infrastructure/restapi/endpoints"
	"github.com/alexjurev/vault-service/pkg/infrastructure/restapi/operations"
)

func setupSwaggerEndpoints(api *operations.VaultServiceAPI, e *endpoints.Endpoints) {
	api.AddObjectHandler = operations.AddObjectHandlerFunc(e.AddObjectEndpoint)
	api.FindObjectHandler = operations.FindObjectHandlerFunc(e.FindObjectEndpoint)
}
